spring:
  application:
    name: stock-analysis-api

  datasource:
    url: jdbc:h2:mem:stockdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.example.stockanalysis: DEBUG


kiwoom:
  grant_type: client_credentials
  secret-key: v6pQbsgskowB0FP3ehW3m6t_M4CMTIX-cJ9Xd_CY_aw
  app-key: Bl-4Kg2mLUjbVAGQM84hD-KZnnUpY6PcUcTZiTU2I3E
  base-url: https://api.kiwoom.com
  mock-base-url: https://mockapi.kiwoom.com